# this is the older kubernetes way of getting load balancing/autoscaling to work

apiVersion: v1
kind: ReplicationController
metadata:
  name: mikeapp-rc
  labels:
     app: mikeapp
	 type: front-end
	 
spec:
  template:
    metadata:
	  name: myapp-pod
	  labels:
	    app: myapp
		type: front-end
	spec:
	  containers:
	  - name: nginx-container
	    image: nginx
		
replicas: 3