- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
    region: "{{ aws_region }}"
    instance_type: "{{ instance_type }}"
    keypair: "{{ keypair_name }}"
    security_groups: "{{ security_group_name }}"
    image_id: "{{ ami_id }}"
    count: 1
    
  tasks:
    
    - name: create instance
      ec2_instance:
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        security_groups: "{{ security_groups }}"
        image_id: "{{ image_id }}"
        count: "{{ count }}"
        instance_tags:
          Name: "{{ name }}"
      register: ec2

    - name: wait for instance to be up and running
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        search_regex: "OpenSSH"
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
