---
- hosts: prod1
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Install security updates
      apt:
        name: "*-security"
        state: latest
